### ISSUE TITLE
Implement correct npm test

### ISSUE THREAD

**Issue by ainthek** [tonthanhhung/string-template-extractor#1]
$ npm test

> string-template-extractor@1.0.0 test C:\workspaces\dmz\string-template-extractor
> echo "Error: no test specified" && exit 1

"Error: no test specified"
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by tonthanhhung** [comment]
@ainthek : fixed by applying your cli-boilerplate template then resolve jshint error from my own.
Readme updated.
